//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidoresInteligentesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medidor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medidor()
        {
            this.Lectura = new HashSet<Lectura>();
        }
    
        public int idMedidor { get; set; }
        public string nombre { get; set; }
        public int idTipo { get; set; }
        public int idUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lectura> Lectura { get; set; }
        public virtual TipoMedidor TipoMedidor { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
